### ISSUE TITLE
I can't handle the websocket.on('error') call back function

### ISSUE THREAD

**Issue by xhacker5000** [kudos/koa-websocket#9]
I can't handle the websocket.on('error') call back function
I test this lib , and I can't handle this event , but the close event is ok

**Comment by hedgerh** [comment]
What errors are you trying to catch?  If you still have some code that could be helpful.

`koa-websocket` uses the `ws` library.  From the sound of the docs, the `error` event is only emitted when something errors out on the client side.  https://github.com/websockets/ws/blob/master/doc/ws.md#event-error-1

If you want to catch errors from calling `websocket.send` on the server side, you need to pass a callback to `websocket.send` that will handle any errors.  If you wanted, you could emit an `error` event from within that callback:

```js
this.websocket.on('error', (err) => { console.log('error emitted:', err) })
this.websocket.on('close', () => {
  this.websocket.send('this will throw an error', (err) => {
    if (err) {
      this.websocket.emit('error', err))
    }
})
```

Please see here for more error handling best practices when using `ws`:  https://github.com/websockets/ws#error-handling-best-practices

@kudos: This should be good to close, since it's not an issue with `koa-websocket`.

**Comment by kudos** [comment]
@hedgerh thanks!
